//Authentication
export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

// Ideas
export const GET_IDEAS_SUCCESS = 'GET_IDEAS_SUCCESS'
export const REQUEST_IDEAS = 'REQUEST_IDEAS'
export const RECEIVE_IDEAS = 'RECEIVE_IDEAS'
export const FAILURE_IDEAS = 'FAILURE_IDEAS'

//get just one idea for viewing/editing.  
export const REQUEST_IDEA = 'REQUEST_IDEA'

export const UPDATE_IDEA_VIEWS_REQUEST = 'UPDATE_IDEA_VIEWS_REQUEST'
export const UPDATE_IDEA_VIEWS_SUCCESS = 'UPDATE_IDEA_VIEWS_SUCCESS'
export const UPDATE_IDEA_VIEWS_FAILURE = 'UPDATE_IDEA_VIEWS_FAILURE'

//search parameters
export const UPDATE_SEARCH_PARAMS = 'UPDATE_SEARCH_PARAMS'
export const REMOVE_SEARCH_PARAM = 'REMOVE_SEARCH_PARAM'

//pagination
export const SET_PAGINATION = 'SET_PAGINATION'
export const UPDATE_PAGE = 'UPDATE_PAGE'

// Categories
export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES'
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES'
export const FAILURE_CATEGORIES = 'FAILURE_CATEGORIES'

export const REQUEST_ADD_CATEGORY = 'REQUEST_ADD_CATEGORY'
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS'
export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE'

export const REQUEST_UPDATE_CATEGORY = 'REQUEST_UPDATE_CATEGORY'
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS'
export const UPDATE_CATEGORY_FAILURE = 'UPDATE_CATEGORY_FAILURE'

export const REQUEST_DELETE_CATEGORY = 'REQUEST_DELETE_CATEGORY'
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS'
export const DELETE_CATEGORY_FAILURE = 'DELETE_CATEGORY_FAILURE'

// Stages
export const REQUEST_STAGES = 'REQUEST_STAGES'
export const RECEIVE_STAGES = 'RECEIVE_STAGES'
export const FAILURE_STAGES = 'FAILURE_STAGES'

export const REQUEST_ADD_STAGE = 'REQUEST_ADD_STAGE'
export const ADD_STAGE_SUCCESS = 'ADD_STAGE_SUCCESS'
export const ADD_STAGE_FAILURE = 'ADD_STAGE_FAILURE'

export const REQUEST_UPDATE_STAGE = 'REQUEST_UPDATE_STAGE'
export const UPDATE_STAGE_SUCCESS = 'UPDATE_STAGE_SUCCESS'
export const UPDATE_STAGE_FAILURE = 'UPDATE_STAGE_FAILURE'

export const REQUEST_DELETE_STAGE = 'REQUEST_DELETE_STAGE'
export const DELETE_STAGE_SUCCESS = 'DELETE_STAGE_SUCCESS'
export const DELETE_STAGE_FAILURE = 'DELETE_STAGE_FAILURE'

// Users
export const REQUEST_USERS = 'REQUEST_USERS'
export const RECEIVE_USERS = 'RECEIVE_USERS'
export const FAILURE_USERS = 'FAILURE_USERS'

// Votes
export const REQUEST_ADD_VOTE = 'REQUEST_ADD_VOTE'
export const ADD_VOTE_SUCCESS = 'ADD_VOTE_SUCCESS'
export const ADD_VOTE_FAILURE = 'ADD_VOTE_FAILURE'

export const REQUEST_UPDATE_VOTE = 'REQUEST_UPDATE_VOTE'
export const UPDATE_VOTE_SUCCESS = 'UPDATE_VOTE_SUCCESS'
export const UPDATE_VOTE_FAILURE = 'UPDATE_VOTE_FAILURE'

export const REQUEST_DELETE_VOTE = 'REQUEST_DELETE_VOTE'
export const DELETE_VOTE_SUCCESS = 'DELETE_VOTE_SUCCESS'
export const DELETE_VOTE_FAILURE = 'DELETE_VOTE_FAILURE'

// Comments
export const REQUEST_ADD_COMMENT = 'REQUEST_ADD_COMMENT'
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE'

export const REQUEST_UPDATE_COMMENT = 'REQUEST_UPDATE_COMMENT'
export const UPDATE_COMMENT_SUCCESS = 'UPDATE_COMMENT_SUCCESS'
export const UPDATE_COMMENT_FAILURE = 'UPDATE_COMMENT_FAILURE'

export const REQUEST_DELETE_COMMENT = 'REQUEST_DELETE_COMMENT'
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE'

export const REQUEST_COMMENTS = 'REQUEST_COMMENTS'
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS'
export const FAIL_REQUEST_COMMENTS = 'FAIL_REQUEST_COMMENTS'

export const REQUEST_FLAGGED_COMMENTS = 'REQUEST_FLAGGED_COMMENTS'
export const RECEIVE_FLAGGED_COMMENTS = 'RECEIVE_FLAGGED_COMMENTS'
export const FAIL_REQUEST_FLAGGED_COMMENTS = 'FAIL_REQUEST_FLAGGED_COMMENTS'

export const REQUEST_REJECTED_COMMENTS = 'REQUEST_REJECTED_COMMENTS'
export const RECEIVE_REJECTED_COMMENTS = 'RECEIVE_REJECTED_COMMENTS'
export const FAIL_REQUEST_REJECTED_COMMENTS = 'FAIL_REQUEST_REJECTED_COMMENTS'

// Replies
export const REQUEST_ADD_REPLY = 'REQUEST_ADD_REPLY'
export const ADD_REPLY_SUCCESS = 'ADD_REPLY_SUCCESS'
export const ADD_REPLY_FAILURE = 'ADD_REPLY_FAILURE'

export const REQUEST_UPDATE_REPLY = 'REQUEST_UPDATE_REPLY'
export const UPDATE_REPLY_SUCCESS = 'UPDATE_REPLY_SUCCESS'
export const UPDATE_REPLY_FAILURE = 'UPDATE_REPLY_FAILURE'

export const REQUEST_DELETE_REPLY = 'REQUEST_DELETE_REPLY'
export const DELETE_REPLY_SUCCESS = 'DELETE_REPLY_SUCCESS'
export const DELETE_REPLY_FAILURE = 'DELETE_REPLY_FAILURE'

